#!/usr/local/php/bin/php
#!/usr/bin/env php
<?php
//echo phpversion();exit( 0);
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');


//add by libin@3ti.us 2017/07/11
Yii::setAlias('@nlp', dirname(dirname(__DIR__)) . '/nlp');


$config = require(__DIR__ . '/config/console.nlp.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
